// <auto-generated />
using System;
using Booking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251029102918_AmenityTable2ndChance")]
    partial class AmenityTable2ndChance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HouseId = 1,
                            Name = "Private Pool"
                        },
                        new
                        {
                            Id = 2,
                            HouseId = 1,
                            Name = "Microwave"
                        },
                        new
                        {
                            Id = 3,
                            HouseId = 1,
                            Name = "Private Balcony"
                        },
                        new
                        {
                            Id = 4,
                            HouseId = 1,
                            Name = "1 king bed and 1 sofa bed"
                        },
                        new
                        {
                            Id = 5,
                            HouseId = 2,
                            Name = "Private Plunge Pool"
                        },
                        new
                        {
                            Id = 6,
                            HouseId = 2,
                            Name = "Microwave and Mini Refrigerator"
                        },
                        new
                        {
                            Id = 7,
                            HouseId = 2,
                            Name = "Private Balcony"
                        },
                        new
                        {
                            Id = 8,
                            HouseId = 2,
                            Name = "king bed or 2 double beds"
                        },
                        new
                        {
                            Id = 9,
                            HouseId = 3,
                            Name = "Private Pool"
                        },
                        new
                        {
                            Id = 10,
                            HouseId = 3,
                            Name = "Jacuzzi"
                        },
                        new
                        {
                            Id = 11,
                            HouseId = 3,
                            Name = "Private Balcony"
                        });
                });

            modelBuilder.Entity("Booking.Domain.Entities.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SqMeters")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description about Big House...",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Big House",
                            Occupancy = 4,
                            Price = 350.0,
                            SqMeters = 600
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description about Uber House...",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Uber House",
                            Occupancy = 3,
                            Price = 250.0,
                            SqMeters = 500
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description about Boss House...",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Boss House",
                            Occupancy = 6,
                            Price = 150.0,
                            SqMeters = 750
                        });
                });

            modelBuilder.Entity("Booking.Domain.Entities.HouseNumber", b =>
                {
                    b.Property<int>("House_Number")
                        .HasColumnType("int");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_Number");

                    b.HasIndex("HouseId");

                    b.ToTable("HouseNumbers");

                    b.HasData(
                        new
                        {
                            House_Number = 101,
                            HouseId = 1
                        },
                        new
                        {
                            House_Number = 102,
                            HouseId = 1
                        },
                        new
                        {
                            House_Number = 103,
                            HouseId = 1
                        },
                        new
                        {
                            House_Number = 104,
                            HouseId = 1
                        },
                        new
                        {
                            House_Number = 201,
                            HouseId = 2
                        },
                        new
                        {
                            House_Number = 202,
                            HouseId = 2
                        },
                        new
                        {
                            House_Number = 203,
                            HouseId = 2
                        },
                        new
                        {
                            House_Number = 301,
                            HouseId = 3
                        },
                        new
                        {
                            House_Number = 302,
                            HouseId = 3
                        });
                });

            modelBuilder.Entity("Booking.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("Booking.Domain.Entities.House", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("Booking.Domain.Entities.HouseNumber", b =>
                {
                    b.HasOne("Booking.Domain.Entities.House", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });
#pragma warning restore 612, 618
        }
    }
}
