// <auto-generated />
using System;
using Booking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251022220226_Seed3ExampleHousesIntoTable")]
    partial class Seed3ExampleHousesIntoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking.Domain.Entities.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SqMeters")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description about Big House...",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Big House",
                            Occupancy = 4,
                            Price = 350.0,
                            SqMeters = 600
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description about Uber House...",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Uber House",
                            Occupancy = 3,
                            Price = 250.0,
                            SqMeters = 500
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description about Boss House...",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Boss House",
                            Occupancy = 6,
                            Price = 150.0,
                            SqMeters = 750
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
